/**
 * Register offsets within a SolarEdge battery status and
 * information block.
 */
export enum SolarEdgeBatteryRegister {

  MANUFACTURER = 0x00,
  MODEL = 0x10,
  FIRMWARE_VERSION = 0x20,
  SERIAL_NUMBER = 0x30,
  DEVICE_ID = 0x40,

  RATED_ENERGY = 0x42,
  MAXIMUM_CHARGE_CONTINUOUS_POWER = 0x44,
  MAXIMUM_DISCHARGE_CONTINUOUS_POWER = 0x46,
  MAXIMUM_CHARGE_PEAK_POWER = 0x48,
  MAXIMUM_DISCHARGE_PEAK_POWER = 0x4A,

  AVERAGE_TEMPERATURE = 0x6C,
  MAXIMUM_TEMPERATURE = 0x6E,
  VOLTAGE = 0x70,
  CURRENT = 0x72,
  POWER = 0x74,

  MAXIMUM_ENERGY = 0x7E,
  AVAILABLE_ENERGY = 0x80,
  STATE_OF_HEALTH = 0x82,
  STATE_OF_ENERGY = 0x84,
  STATUS = 0x86,
  STATUS_INTERNAL = 0x88,

}
