/**
 * Register offsets for SunSpec Model 120:
 * Inverter Controls Nameplate Ratings.
 *
 * Offsets are relative to the first data register after
 * the model ID and model-length registers.
 *
 * Model length: 26 registers.
 */
export enum NameplateModel120Register {
  DER_TYPE = 0,

  CONTINUOUS_ACTIVE_POWER_RATING = 1,
  CONTINUOUS_ACTIVE_POWER_SCALE_FACTOR = 2,

  CONTINUOUS_APPARENT_POWER_RATING = 3,
  CONTINUOUS_APPARENT_POWER_SCALE_FACTOR = 4,

  CONTINUOUS_REACTIVE_POWER_RATING_QUADRANT_1 = 5,
  CONTINUOUS_REACTIVE_POWER_RATING_QUADRANT_2 = 6,
  CONTINUOUS_REACTIVE_POWER_RATING_QUADRANT_3 = 7,
  CONTINUOUS_REACTIVE_POWER_RATING_QUADRANT_4 = 8,
  CONTINUOUS_REACTIVE_POWER_SCALE_FACTOR = 9,

  MAXIMUM_AC_CURRENT_RATING = 10,
  MAXIMUM_AC_CURRENT_SCALE_FACTOR = 11,

  MINIMUM_POWER_FACTOR_RATING_QUADRANT_1 = 12,
  MINIMUM_POWER_FACTOR_RATING_QUADRANT_2 = 13,
  MINIMUM_POWER_FACTOR_RATING_QUADRANT_3 = 14,
  MINIMUM_POWER_FACTOR_RATING_QUADRANT_4 = 15,
  MINIMUM_POWER_FACTOR_SCALE_FACTOR = 16,

  NOMINAL_ENERGY_RATING = 17,
  NOMINAL_ENERGY_SCALE_FACTOR = 18,

  AMP_HOUR_RATING = 19,
  AMP_HOUR_RATING_SCALE_FACTOR = 20,

  MAXIMUM_CHARGE_RATE = 21,
  MAXIMUM_CHARGE_RATE_SCALE_FACTOR = 22,

  MAXIMUM_DISCHARGE_RATE = 23,
  MAXIMUM_DISCHARGE_RATE_SCALE_FACTOR = 24,

  PAD = 25,
}